import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";

import { LoginForm } from "@/components";
import React from "react";
import WelcomePage from "./welcome-page";

const Home: React.FunctionComponent = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data, status } = useSession();
  return (
    <>
      <Head>
        <title>Crimson Paints</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {status === "authenticated" ? <WelcomePage /> : <LoginForm />}
      </main>
    </>
  );
};
export default Home;
